CREATE DATABASE IF NOT EXISTS mydb CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS mydb.user (id INT UNSIGNED NOT NULL AUTO_INCREMENT, chara_id INT UNSIGNED NOT NULL, created_at DATETIME, updated_at DATETIME, PRIMARY KEY(`id`)) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS mydb.room (id INT UNSIGNED NOT NULL AUTO_INCREMENT, size INT UNSIGNED NOT NULL, members TEXT, created_at DATETIME, updated_at DATETIME, PRIMARY KEY(`id`)) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS mydb.action_log (id INT UNSIGNED NOT NULL AUTO_INCREMENT, room_id INT UNSIGNED NOT NULL, user_id INT UNSIGNED NOT NULL, log TEXT, created_at DATETIME, PRIMARY KEY(`id`)) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- ALTER TABLE mydb.user ADD INDEX room_idx(room_id);
